### ISSUE TITLE
Posted Config.json throws error.

### ISSUE THREAD

**Issue by ItsRainingHP** [cheeseandcereal/transmission_influxdb_exporter#2]
Hello, I have been trying to get your container to work but the config provided throws an error. Here is the config's I have tried and their errors. Are you able to assist? Thank you!

Default:
```
{
  "seconds_between_collections": 60,  // time to wait between finished transmission scrapes
  "influxdb": {
    "host_addr": "HIDDEN",
    "host_port": 8086,
    "use_ssl": false,
    "verify_ssl": false,
    "database": "transmission",  // database will be created if it doesn't exist (don't change if using provided grafana dashboard)
    "username": "root",  // if authentication is disabled on influxdb, leave user/pass as-is
    "password": "root"
  },
  "transmission_clients": [  // Specify as many as desired
    {
      "name": "transmission",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "HIDDEN",
      "rpc_port": 9092,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "admin",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60,  // how long to allow an RPC request to take before timing out with an error
    }
  ]
}
```

Output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/transmission_influxdb/main.py", line 41, in <module>
    main()
  File "/usr/src/app/transmission_influxdb/main.py", line 16, in main
    transmission_clients: List[transmission.TransmissionClient] = [transmission.TransmissionClient(x) for x in config.get_torrent_client_configs()]
  File "/usr/src/app/transmission_influxdb/config.py", line 76, in get_torrent_client_configs
    _load_config_if_necessary()
  File "/usr/src/app/transmission_influxdb/config.py", line 11, in _load_config_if_necessary
    config_cache = json.load(f)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 39 (char 40)
```

Config:
```
{
  "seconds_between_collections": 60,
  "influxdb": {
    "host_addr": "HIDDEN",
    "host_port": 8086,
    "use_ssl": false,
    "verify_ssl": false,
    "database": "transmission",
    "username": "root",
    "password": "root"
  },
  "transmission_clients": [
    {
      "name": "transmission-radarr",
      "rpc_addr": "HIDDEN",
      "rpc_port": 9092,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "admin",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,
      "rpc_timeout": 60,
    }
  ]
}
```

Output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/transmission_influxdb/main.py", line 41, in <module>
    main()
  File "/usr/src/app/transmission_influxdb/main.py", line 16, in main
    transmission_clients: List[transmission.TransmissionClient] = [transmission.TransmissionClient(x) for x in config.get_torrent_client_configs()]
  File "/usr/src/app/transmission_influxdb/config.py", line 76, in get_torrent_client_configs
    _load_config_if_necessary()
  File "/usr/src/app/transmission_influxdb/config.py", line 11, in _load_config_if_necessary
    config_cache = json.load(f)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 22 column 5 (char 539)
```

**Comment by ItsRainingHP** [comment]
I found the error. There is an extra comma in the last variable for transmission clients. Here is a working one for those reading.

```
{
  "seconds_between_collections": 60,  // time to wait between finished transmission scrapes
  "influxdb": {
    "host_addr": "HIDDEN",
    "host_port": 8086,
    "use_ssl": false,
    "verify_ssl": false,
    "database": "transmission",  // database will be created if it doesn't exist (don't change if using provided grafana dashboard)
    "username": "root",  // if authentication is disabled on influxdb, leave user/pass as-is
    "password": "root"
  },
  "transmission_clients": [  // Specify as many as desired
    {
      "name": "transmission",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "HIDDEN",
      "rpc_port": 9092,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "admin",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60  // how long to allow an RPC request to take before timing out with an error
    }
  ]
}
```
Also for those reading. If you want multiple. It is listed like this:

```
{
  "seconds_between_collections": 60,  // time to wait between finished transmission scrapes
  "influxdb": {
    "host_addr": "HIDDEN",
    "host_port": 8086,
    "use_ssl": false,
    "verify_ssl": false,
    "database": "transmission",  // database will be created if it doesn't exist (don't change if using provided grafana dashboard)
    "username": "root",  // if authentication is disabled on influxdb, leave user/pass as-is
    "password": "root"
  },
  "transmission_clients": [  // Specify as many as desired
    {
      "name": "transmission",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "HIDDEN",
      "rpc_port": 9092,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "admin",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60  // how long to allow an RPC request to take before timing out with an error
      "name": "transmission2",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "HIDDEN",
      "rpc_port": 9092,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "admin",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60  // how long to allow an RPC request to take before timing out with an error
      "name": "transmission3",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "HIDDEN",
      "rpc_port": 9092,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "admin",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60  // how long to allow an RPC request to take before timing out with an error
    }
  ]
}

**Comment by ItsRainingHP** [comment]
The fact that you have to use the Flux query language. Which ultimately stores your data on Amazon, Google or Microsoft servers seems like a big risk when trying to building a torrents dashboard. Why would I want my torrent data stored on someone else's servers and potentially available to others should said service choose to do so.

**Comment by cheeseandcereal** [comment]
What? The flux query language has nothing to do with the cloud. It's just the new query language for influxdb.

**Comment by ItsRainingHP** [comment]
I understand that and I hope you can help me here but according to the flux setup page they require a token and bucket which is linked to one of the services mentioned above.

![image](https://user-images.githubusercontent.com/79205731/126574782-25a35ae4-f399-4bca-b7a3-80694f59688d.png)

**Comment by ItsRainingHP** [comment]
Alright. Ignore this. I definitely was using DB 1.8.6. After creating a second db 2.0 container for this I see you make said items in the InfluxDB Dashboard.

**Comment by ItsRainingHP** [comment]
I think I understand now. I needed to create a token and bucket using the CLI since this is 1.X and not 2.0.

**Comment by ItsRainingHP** [comment]
Hello @cheeseandcereal I am sorry to bother you. I believe I got your container to connect to my Influxdb 1.8.6 instance. However, I cannot get Grafana v8.0.6 to connect to the database.

To my understanding the settings should be something like this:

![image](https://user-images.githubusercontent.com/79205731/126868709-2c49225f-feee-48f5-9d17-d53119d2ecb9.png)

I have tried with Skip TLS Verify unchecked as well. Thus:

Organization: any string to my understanding
Token: user:pass (I have tried root:root and leaving blank, I have auth disabled)
Default Bucket: transmission (I have tried transmission, transmission/autogen, and leaving it blank)

Thank you for your time. I appreciate it.

**Comment by cheeseandcereal** [comment]
Skip TLS verify doesn't disable TLS, it's just skips checking the validity of the certificate for use with self-signing and whatnot. You probably just need to manually specify http since it defaults to https so change the server url to http://192.168.0.216:8086

**Comment by ItsRainingHP** [comment]
Still fails for me

![image](https://user-images.githubusercontent.com/79205731/126887130-077151e0-87ef-458d-bfa1-47e2884da034.png)

My config for this container is the same as original post.

Output Log for transmission_influxdb_exporter container:

```
INFO:main:Transmission client transmission-sonarr 7 points found for recording
INFO:main:Writing 7 data points to influxdb
INFO:main:Transmission client transmission-sonarr 7 points found for recording
INFO:main:Writing 7 data points to influxdb
INFO:main:Transmission client transmission-sonarr 7 points found for recording
INFO:main:Writing 7 data points to influxdb
```

Here is the last few lines of my influxdb:

```
[httpd] 172.17.0.1 - root [24/Jul/2021:20:51:05 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" 8983513e-ecfb-11eb-b4e4-0242ac11000a 995060
[httpd] 172.17.0.1 - root [24/Jul/2021:20:51:06 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 8a1bb6bb-ecfb-11eb-b4e5-0242ac11000a 62098
[httpd] 172.17.0.1 - root [24/Jul/2021:20:51:06 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 8a26fc8c-ecfb-11eb-b4e6-0242ac11000a 33657
[httpd] 172.17.0.1 - root [24/Jul/2021:20:52:06 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" adfef05e-ecfb-11eb-b4ea-0242ac11000a 1400363
[httpd] 172.17.0.1 - root [24/Jul/2021:20:52:07 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" aed52dab-ecfb-11eb-b4eb-0242ac11000a 235992
[httpd] 172.17.0.1 - root [24/Jul/2021:20:52:08 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" aefa569b-ecfb-11eb-b4ec-0242ac11000a 66662
[httpd] 172.17.0.1 - root [24/Jul/2021:20:53:08 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" d2d6d889-ecfb-11eb-b4ef-0242ac11000a 661810
[httpd] 172.17.0.1 - root [24/Jul/2021:20:53:08 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" d33c90ac-ecfb-11eb-b4f0-0242ac11000a 107508
[httpd] 172.17.0.1 - root [24/Jul/2021:20:53:09 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" d34e6524-ecfb-11eb-b4f1-0242ac11000a 25254
[httpd] 172.17.0.1 - root [24/Jul/2021:20:54:09 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" f725715e-ecfb-11eb-b4f4-0242ac11000a 2263818
[httpd] 172.17.0.1 - root [24/Jul/2021:20:54:11 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" f87f6090-ecfb-11eb-b4f5-0242ac11000a 106469
[httpd] 172.17.0.1 - root [24/Jul/2021:20:54:11 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" f890b73a-ecfb-11eb-b4f6-0242ac11000a 21506
[httpd] 172.17.0.1 - root [24/Jul/2021:20:55:11 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" 1c65eb76-ecfc-11eb-b4ff-0242ac11000a 1614276
[httpd] 172.17.0.1 - root [24/Jul/2021:20:55:13 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 1d5d0480-ecfc-11eb-b500-0242ac11000a 93833
[httpd] 172.17.0.1 - root [24/Jul/2021:20:55:13 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 1d6ccb6b-ecfc-11eb-b501-0242ac11000a 24446
```

Here is the InfluxDB Config.yml:

```
[http]
  enabled = true
  flux-enabled=true
  bind-address = "192.168.0.216:8086"
  auth-enabled = false # Set to true
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  pprof-auth-enabled = false
  debug-pprof-enabled = false
  ping-auth-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
```

**Comment by phife-dawg** [comment]
@cheeseandcereal I am also having trouble configuring the data source in Grafana. Perhaps you could post a screenshot of your working one? I am not sure how to fill in the InfluxDB details section.

**Comment by cheeseandcereal** [comment]
I've posted a picture of my configuration here: https://github.com/cheeseandcereal/transmission_influxdb_exporter/issues/3#issuecomment-1007799033
