### ISSUE TITLE
Error when running in Docker

### ISSUE THREAD

**Issue by phife-dawg** [cheeseandcereal/transmission_influxdb_exporter#5]
Hello! I am running this in docker on Unraid 6.9.2 and getting the following error:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/src/app/transmission_influxdb/main.py", line 41, in <module>
main()
File "/usr/src/app/transmission_influxdb/main.py", line 16, in main
transmission_clients: List[transmission.TransmissionClient] = [transmission.TransmissionClient(x) for x in config.get_torrent_client_configs()]
File "/usr/src/app/transmission_influxdb/config.py", line 79, in get_torrent_client_configs
_load_config_if_necessary()
File "/usr/src/app/transmission_influxdb/config.py", line 11, in _load_config_if_necessary
config_cache = json.load(f)
File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 38 (char 39)
```

Here is my config file:

```
{
  "seconds_between_collections": 5,  // time to wait between finished transmission scrapes
  "influxdb": {
    "host_addr": "http://192.168.68.16",
    "host_port": 8086,
    "use_ssl": false,
    "verify_ssl": false,
    "database": "transmission",  // database will be created if it doesn't exist (don't change if using provided grafana dashboard)
    "username": "root",  // if authentication is disabled on influxdb, leave user/pass as-is
    "password": "root"
  },
  "transmission_clients": [  // Specify as many as desired
    {
      "name": "trmn-buffer-0",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "http://192.168.86.16",
      "rpc_port": 1001,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "HIDDEN",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60,  // how long to allow an RPC request to take before timing out with an error
      "disable_individual_torrent_collection": false  // optional boolean which can disable making points for individual torrents (significantly reduces influxdb usage but some dashboard graphs won't work)
    },
    {
      "name": "trmn-library-0",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "http://192.168.86.16",
      "rpc_port": 9091,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "HIDDEN",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60,  // how long to allow an RPC request to take before timing out with an error
      "disable_individual_torrent_collection": false  // optional boolean which can disable making points for individual torrents (significantly reduces influxdb usage but some dashboard graphs won't work)
    },
    {
      "name": "trmn-radarr-1",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "http://192.168.86.16",
      "rpc_port": 1011,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "HIDDEN",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60,  // how long to allow an RPC request to take before timing out with an error
      "disable_individual_torrent_collection": false  // optional boolean which can disable making points for individual torrents (significantly reduces influxdb usage but some dashboard graphs won't work)
    },
    {
      "name": "trmn-radarrUHD-1",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "http://192.168.86.16",
      "rpc_port": 1012,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "HIDDEN",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60,  // how long to allow an RPC request to take before timing out with an error
      "disable_individual_torrent_collection": false  // optional boolean which can disable making points for individual torrents (significantly reduces influxdb usage but some dashboard graphs won't work)
    },
    {
      "name": "trmn-sonarr-1",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "http://192.168.86.16",
      "rpc_port": 1021,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "HIDDEN",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60,  // how long to allow an RPC request to take before timing out with an error
      "disable_individual_torrent_collection": false  // optional boolean which can disable making points for individual torrents (significantly reduces influxdb usage but some dashboard graphs won't work)
    },
    {
      "name": "trmn-sonarrUHD-1",  // The name used to tag db datapoints with for this transmission daemon. Useful to make unique when you have more than one client
      "rpc_addr": "http://192.168.86.16",
      "rpc_port": 1022,
      "rpc_path": "/transmission/rpc",
      "rpc_user": "HIDDEN",
      "rpc_password": "HIDDEN",
      "rpc_verified_tls": false,  // note that unverified ssl/tls (such as with self-signed cert) is not currently supported
      "rpc_timeout": 60,  // how long to allow an RPC request to take before timing out with an error
      "disable_individual_torrent_collection": false  // optional boolean which can disable making points for individual torrents (significantly reduces influxdb usage but some dashboard graphs won't work)
    }
  ]
}
```

**Comment by cheeseandcereal** [comment]
remove the comments to make it valid json. You can use some json linter to validate that you have valid json: https://duckduckgo.com/?t=ffab&q=json+linter&ia=answer

**Comment by phife-dawg** [comment]
That did it, thanks!
